server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/produto
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  artemis:
    mode: native
    broker-url: ${JMS_BROKER_URL:tcp://localhost:61616}
    user: arthur
    password: live